<?php
/**
 * Handles Gutenberg Table Block registration.
 *
 * @since 1.0.0
 *
 * @package Ivan_Api_Based\Gutenberg
 */

namespace Ivan_Api_Based\Gutenberg;

/**
 * Class Table_Block.
 *
 * @since 1.0.0
 */
class Table_Block {

	/**
	 * Initialize hooks for registering the block.
	 *
	 * @since 1.0.0
	 */
	public function hooks() {
		add_action( 'init', [ $this, 'register_block' ] );
	}

	/**
	 * Registers the block using metadata from block.json.
	 *
	 * @since 1.0.0
	 */
	public function register_block() {
		register_block_type( IVAN_API_BASED_PATH . '/build' );

		// This ID matches the handle auto-generated by block.json.
		wp_localize_script(
			'ivan-hrk-api-based-addon-editor-script',
			'IvanApiBasedAddon',
			[
				'ajax_url' => admin_url( 'admin-ajax.php' ),
				'nonce'    => wp_create_nonce( 'ivan_api_based_nonce' ),
			]
		);

		// Handle for the view script.
		wp_localize_script(
			'ivan-hrk-api-based-addon-view-script',
			'IvanApiBasedAddon',
			[
				'ajax_url' => admin_url( 'admin-ajax.php' ),
				'nonce'    => wp_create_nonce( 'ivan_api_based_nonce' ),
			]
		);
	}
}
